spring:
  mail:
    host: smtp.gmail.com
    username: hadchityjoe64@gmail.com
    password: hfdy uzcn hpeh guyp
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true